name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@v1.139.0
      - uses: taiga-family/ci/actions/setup/node@v1.139.0
      - run: |
          npm run prettier -- --check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
