name: ⚙️ Update Submodules and Create PR
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Update all submodules to latest commits
        id: update
        run: |
          git submodule update --remote --recursive
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            git commit -m "chore: update submodules to latest commits"
          fi

      - name: Create Pull Request
        if: steps.update.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'submodule-update-$(date +%s)'
          commit-message: 'chore: update submodules'
          title: "Submodule Updates $(date +'%Y-%m-%d')"
          body: 'Automated update of Git submodules to their latest commits.'
          labels: 'dependencies, automated'
          base: 'main'
