name: ⚙️ Update Submodules and Create PR
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write # Allows pushing

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/variables@v1.142.0

      - name: Update all submodules to latest commits
        id: update
        run: |
          git submodule update --remote --recursive
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            git commit -m "chore: update submodules to latest commits"
          fi

      - name: Create Pull Request
        if: steps.update.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          branch: submodule-update
          commit-message: 'chore: update submodules'
          title: Submodule Updates
          body: Automated update of Git submodules to their latest commits
          base: main
